Update e2e.yaml

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -1760,7 +1760,7 @@ jobs:
               if ssh -i ~/.ssh/temp-id_rsa -o StrictHostKeyChecking=no opc@"${{ env.INSTANCE_IP }}" "sudo podman exec $CONTAINER_NAME test -f $TENANCY_CONFIG_PATH" 2>>"$LOG_FILE"; then
                 if [ "$FORCE_UPDATE" = "true" ]; then
                   echo "force_update_prefix is true, forcing update for prefix: $PREFIX" | tee -a "$LOG_FILE"
-                  ssh -i ~/.ssh/temp-id_rsa -o StrictHostKeyChecking=no opc@"${{ env.INSTANCE_IP }}" "sudo podman exec $CONTAINER_NAME bash -c 'cd /cd3user/oci_tools/cd3_automation_toolkit/user-scripts/ && echo \"y\" | python createTenancyConfig.py $TENANCY_CONFIG_PATH'" >> "$LOG_FILE" 2>&1 || { echo "Error: Failed to run createTenancyConfig.py for $PREFIX" | tee -a "$LOG_FILE"; exit 1; }
+                  ssh -i ~/.ssh/temp-id_rsa -o StrictHostKeyChecking=no opc@"${{ env.INSTANCE_IP }}" "sudo podman exec $CONTAINER_NAME bash -c 'cd /cd3user/oci_tools/cd3_automation_toolkit/user-scripts/ && echo "y" | python createTenancyConfig.py $TENANCY_CONFIG_PATH'" >> "$LOG_FILE" 2>&1 || { echo "Error: Failed to run createTenancyConfig.py for $PREFIX" | tee -a "$LOG_FILE"; exit 1; }
                   echo "createTenancyConfig.py completed with forced update for $PREFIX" | tee -a "$LOG_FILE"
                 else
                   echo "force_update_prefix is false, skipping createTenancyConfig.py for existing prefix: $PREFIX" | tee -a "$LOG_FILE"
