Update e2e.yaml

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -507,10 +507,10 @@ jobs:
                 ssh -i ~/.ssh/temp-id_rsa -o StrictHostKeyChecking=no opc@${{ env.INSTANCE_IP }} "rm /tmp/tenancyconfig.properties" 2>>"$LOG_FILE" || { echo "Error: Failed to remove temporary tenancy config" | tee -a "$LOG_FILE"; exit 1; }
                 echo "tenancyconfig.properties copied to container" | tee -a "$LOG_FILE"
                 echo "Checking Python in container..." | tee -a "$LOG_FILE"
-                ssh -i ~/.ssh/temp-id_rsa -o StrictHostKeyChecking=no opc@${{ env.INSTANCE_IP }} "sudo podman exec $CONTAINER_ID bash -c 'command -v python >/dev/null || echo \"alias python=python3\" >> ~/.bashrc'" 2>>"$LOG_FILE" || { echo "Error: Failed to set Python alias in container" | tee -a "$LOG_FILE"; exit 1; }
+                ssh -i ~/.ssh/temp-id_rsa -o StrictHostKeyChecking=no opc@${{ env.INSTANCE_IP }} "sudo podman exec $CONTAINER_ID bash -c 'command -v python3 >/dev/null || { echo \"Error: python3 not found in container\" >> $LOG_FILE; exit 1; }'" 2>>"$LOG_FILE" || { echo "Error: Python3 check failed in container" | tee -a "$LOG_FILE"; exit 1; }
                 echo "Running createTenancyConfig.py..." | tee -a "$LOG_FILE"
                 for i in {1..5}; do
-                  if ssh -i ~/.ssh/temp-id_rsa -o StrictHostKeyChecking=no opc@${{ env.INSTANCE_IP }} "sudo podman exec $CONTAINER_ID bash -c 'source ~/.bashrc && cd /cd3user/oci_tools/cd3_automation_toolkit/user-scripts/ && python createTenancyConfig.py tenancyconfig.properties'" >> "$LOG_FILE" 2>&1; then
+                  if ssh -i ~/.ssh/temp-id_rsa -o StrictHostKeyChecking=no opc@${{ env.INSTANCE_IP }} "sudo podman exec $CONTAINER_ID bash -c 'bash -c 'alias python=python3 && cd /cd3user/oci_tools/cd3_automation_toolkit/user-scripts/ && python createTenancyConfig.py tenancyconfig.properties'" >> "$LOG_FILE" 2>&1; then
                     echo "Environment initialization completed successfully" | tee -a "$LOG_FILE"
                     break
                   else
