Update e2e.yaml

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -176,19 +176,21 @@ jobs:
           fi
       
           echo "✅ STACK_ID: $STACK_ID"
+          echo "$STACK_ID" > stack_id.txt
 
       - name: Apply Resource Manager stack
         env:
           OCI_REGION: "us-phoenix-1"
         run: |
-          COMPARTMENT_OCID=$(jq -r '.instance_compartment_ocid' $GITHUB_WORKSPACE/variables.json)
-          STACK_ID=$(oci resource-manager stack list --compartment-id "$COMPARTMENT_OCID" --display-name "CD3-WorkVM-Stack-${{ github.ref_name }}" --region "$OCI_REGION" --query "data[0].id" --raw-output)
+          # COMPARTMENT_OCID=$(jq -r '.instance_compartment_ocid' $GITHUB_WORKSPACE/variables.json)
+          # STACK_ID=$(oci resource-manager stack list --compartment-id "$COMPARTMENT_OCID" --display-name "CD3-WorkVM-Stack-${{ github.ref_name }}" --region "$OCI_REGION" --query "data[0].id" --raw-output)
 
-          if [ -z "$STACK_ID" ]; then
-            echo "Error: Stack ID not found for applying"
-            exit 1
-          fi
+          # if [ -z "$STACK_ID" ]; then
+          #   echo "Error: Stack ID not found for applying"
+          #   exit 1
+          # fi
 
+          STACK_ID=$(cat stack_id.txt)
           echo "Applying Resource Manager stack $STACK_ID in region $OCI_REGION"
           oci resource-manager job create-apply-job \
             --auth instance_principal  \
@@ -201,6 +203,7 @@ jobs:
         run: |
           rm -f variables.json
           rm -f cd3_stack.zip
+          rm -rf stack_id.txt
 
       - name: Say hello
         run: echo "✅ Self-hosted runner is working!"
